version: '3'
services:
  app:
    container_name: deliva_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    restart: on-failure
    volumes:
      - deliva:/usr/src/app/
    depends_on:
      - deliva-postgres
    networks:
      - deliva

  deliva-postgres:
    image: postgres:latest
    container_name: deliva_db
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
    ports:
      - 5432
    networks:
      - deliva

volumes:
  deliva:

# Networks to be created to facilitate communication between containers
networks:
  deliva:
    driver: bridge